<?php

namespace Test\Bundle\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PropertyProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyProviderRepository extends EntityRepository
{
}
