<?php

namespace Test\Bundle\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SharedRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharedRoomRepository extends EntityRepository
{
}
