<?php

namespace Test\Bundle\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserProviderInterface;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserProviderInterface{
    
    private $university = 12;
    
    public function FindUserNameOrEmailInUniversity($username, $university){
        return $this->createQueryBuilder('enduser')
            ->where('enduser.university = :university')
            ->andWhere('enduser.username = :username OR enduser.email = :email')
            ->setParameter('university', $university)
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }

    public function loadUserByUsername($username) {
        $user = $this->FindUserNameOrEmailInUniversity($username, $this->university);
        if(!$user){
            throw new \Symfony\Component\Security\Core\Exception\UsernameNotFoundException('user name '.$username.' not found');
        }
        return $user;
    }

    public function refreshUser(\Symfony\Component\Security\Core\User\UserInterface $user) {
        return $user;
    }

    public function supportsClass($class) {
        return;
    }
}