homepage:
    path:     /{_locale}/
    host:     "{domain}"
    defaults:
        _controller: WebsiteBundle:Home:home
    requirements:
        domain: eduflats.com|www.eduflats.com
        _locale: fr_FR|
        
homepage_restrict:
    path:     /{slug}
    host:     "{domain}"
    defaults:
        _controller: WebsiteBundle:Notfound:notfound
    requirements:
        domain: eduflats.com|www.eduflats.com

subdomain_homepage:
    path:     /
    defaults: { _controller: EduflatsBundle:Search:search }
  
eduflats:
    resource: "@EduflatsBundle/Controller/"
    type:     annotation
    prefix:   /

website:
    resource: "@WebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile