security:
    encoders:
        Eduflats\Bundle\EduflatsBundle\Entity\Student: bcrypt
        Eduflats\Bundle\EduflatsBundle\Entity\PropertyProvider: bcrypt
        Eduflats\Bundle\EduflatsBundle\Entity\Admin: bcrypt
        Eduflats\Bundle\EduflatsBundle\Entity\Client: bcrypt

        #each entity needs its own encoder as specified here

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

#    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

#    providers:
#        end_user:
#            id: user_provider


    providers:
        chain_providers:
            chain:
                providers: [student, property_provider, Admin, Client]
        student:
            entity: { class:EduflatsBundle:Student }
        property_provider:
            entity: { class:EduflatsBundle:PropertyProvider }
        admin:
            entity: { class:EduflatsBundle:Admin }
        client:
            entity: { class:EduflatsBundle:Client }


    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login
                login_path: loginForm
            logout:
                path:   logout
                target: home
            anonymous: true

    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/user, roles: ROLE_USER }
#        - { path: ^/provider, roles: ROLE_PROVIDER }