<?php

namespace Eduflats\Bundle\EduflatsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthenticationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthenticationTypeRepository extends EntityRepository
{
}
