<?php

namespace Eduflats\Bundle\EduflatsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HexValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HexValueRepository extends EntityRepository
{
}
