<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-08-05 09:11:21.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Eduflats\Bundle\EduflatsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\PropertyType
 *
 * @ORM\Entity(repositoryClass="PropertyTypeRepository")
 * @ORM\Table()
 */
class PropertyType
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $nPropertyType;

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\PropertyType
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Set nPropertyType
     *
     * @param integer $nPropertyType
     * @return PropertyType
     */
    public function setNPropertyType($nPropertyType)
    {
        $this->nPropertyType = $nPropertyType;

        return $this;
    }

    /**
     * Get nPropertyType
     *
     * @return integer 
     */
    public function getNPropertyType()
    {
        return $this->nPropertyType;
    }

}
