<?php

namespace Eduflats\Bundle\EduflatsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UniversityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversityRepository extends EntityRepository
{
}
